services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\A11yByDefault\:
    resource: '../Classes/*'

  WebVision\A11yByDefault\Controller\Pa11yController:
    public: true
